name: GitHub Actions Demo
on: 
  push:
    branches:
      - staging
      - main
jobs:
  staging-deploy:
    name: "Staging Deploy"
    if: github.ref_name == 'staging'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out repository
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
        name: Set up Node.js
      - run: ls -l
      - run: npm i
      - run: npm run build
      
  production-deploy:
    name: "Production Deploy"
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out repository
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
        name: Set up Node.js
      - run: ls -l
      - run: npm i
      - run: npm run build


