name: GitHub Actions Demo
on: 
  push:
    branches:
      - staging
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 Hello World"
      - run: echo "Building my project...."


